[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[context.production.environment]
  REACT_APP_API_URL = "https://binary-signals-api.onrender.com"
